default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ":lipstick: 格式化代码"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: weekly
  autoupdate_commit_msg: ":lipstick: 自动格式化代码"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        stages: [commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [commit]